export type PdfDocStatus = "READY" | "PDF_PENDING" | "INTERNAL_ONLY";

export interface PdfDocumentRecord {
  readonly id: string;
  readonly title: string;
  readonly subtitle: string;
  readonly audience: string;
  readonly category:
    | "Core Platform"
    | "Onboarding / KYC"
    | "RWA / Asset Packages"
    | "Funding Routes"
    | "XRPL / IOU / Wallets"
    | "Legacy / Buyback / LP Review"
    | "PATE-COAL-001";
  readonly description: string;
  readonly pdfPath: string;
  readonly version: string;
  readonly status: PdfDocStatus;
  readonly relatedRoutes: readonly string[];
  readonly requiredFor: readonly string[];
  readonly jsonExportAvailable: boolean;
  readonly primaryCtaLabel: "Download PDF";
  readonly secondaryCtaLabel?: "Technical JSON";
  readonly safetyNote?: string;
}

const SAFETY =
  "TROPTIONS materials are provided for informational and due-diligence purposes only. TROPTIONS is not a bank, broker-dealer, exchange, custodian, licensed financial institution, investment adviser, or legal adviser. No live custody, exchange, stablecoin issuance, IOU issuance, Aave execution, token buyback, liquidity pool execution, mining operation, or public investment functionality is enabled. All execution requires legal, compliance, provider, custody, signer, and governance approvals.";

export const PDF_DOCUMENT_REGISTRY: readonly PdfDocumentRecord[] = [
  {
    id: "troptions-platform-overview",
    title: "TROPTIONS Platform Overview",
    subtitle: "Architecture, Compliance & Participant Guide",
    audience: "All participants, lenders, partners",
    category: "Core Platform",
    description:
      "High-level overview of the TROPTIONS ecosystem: Layer 1 architecture, token supply, compliance framework, brand entities, participant roles, and governance model.",
    pdfPath: "/troptions/downloads/troptions-platform-overview.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions", "/troptions/layer1", "/troptions/ecosystem"],
    requiredFor: ["Initial onboarding review", "Lender due diligence", "Partner intake"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "kyc-onboarding-handbook",
    title: "KYC / Onboarding Handbook",
    subtitle: "Identity Verification, Document Submission & DID",
    audience: "Participants, operators, asset owners",
    category: "Onboarding / KYC",
    description:
      "Step-by-step onboarding guide: required documents, document hash submission, KYC tier levels, oracle attestation, and DID anchoring on XRPL.",
    pdfPath: "/troptions/downloads/kyc-onboarding-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/kyc", "/troptions/onboarding"],
    requiredFor: ["Participant onboarding", "Operator clearance", "Asset owner intake"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "rwa-tokenisation-handbook",
    title: "RWA Tokenisation Handbook",
    subtitle: "Gemstones, Real Estate, Equipment & More",
    audience: "Asset owners, attorneys, lenders",
    category: "RWA / Asset Packages",
    description:
      "Complete reference for real-world asset tokenisation: asset eligibility, custody requirements, SPV structure, due diligence process, and approval gates.",
    pdfPath: "/troptions/downloads/rwa-tokenisation-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa", "/troptions/rwa/axl-001"],
    requiredFor: ["RWA intake", "Asset tokenisation approval", "Lender RWA review"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "carbon-credit-handbook",
    title: "Carbon Credit Handbook",
    subtitle: "Sale, Retirement & Registry Procedures",
    audience: "Carbon market participants, compliance officers",
    category: "RWA / Asset Packages",
    description:
      "Procedures for carbon credit sale and permanent retirement on Verra VCS, Gold Standard, ACR, or equivalent registries with full audit trail.",
    pdfPath: "/troptions/downloads/carbon-credit-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/carbon", "/troptions/transactions"],
    requiredFor: ["Carbon credit transaction approval", "Registry retirement"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "bitcoin-settlement-handbook",
    title: "Bitcoin Settlement Handbook",
    subtitle: "VASP Procedures, Travel Rule & Compliance",
    audience: "Settlement desks, compliance officers, lenders",
    category: "Funding Routes",
    description:
      "Reference for Bitcoin settlement preferences: VASP selection, wallet screening, Travel Rule compliance (≥$1,000), and source-of-funds requirements.",
    pdfPath: "/troptions/downloads/bitcoin-settlement-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/settlement", "/troptions/payment-rails"],
    requiredFor: ["BTC settlement approval", "VASP compliance"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "xrpl-iou-issuance-handbook",
    title: "XRPL IOU Issuance Handbook",
    subtitle: "Trustlines, Gateways & Compliance",
    audience: "Web3 operators, XRPL participants, compliance teams",
    category: "XRPL / IOU / Wallets",
    description:
      "Complete guide to XRPL IOU issuance via the TROPTIONS gateway: trustline setup, transfer fees, KYC requirements, and compliance controls. All issuance is gated and simulation-only until approvals complete.",
    pdfPath: "/troptions/downloads/xrpl-iou-issuance-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/xrpl-iou", "/troptions/xrpl-platform", "/troptions/stablecoins"],
    requiredFor: ["IOU issuance approval", "XRPL gateway onboarding"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "funding-routes-handbook",
    title: "Funding Routes Handbook",
    subtitle: "Route Selection, Requirements & Approval Gates",
    audience: "Asset owners, lenders, deal sponsors",
    category: "Funding Routes",
    description:
      "Detailed guide to all TROPTIONS funding routes: route eligibility matrix, document requirements, approval gates, lender scoring, and route verification procedures.",
    pdfPath: "/troptions/downloads/funding-routes-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/funding"],
    requiredFor: ["Funding route selection", "Lender submission"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "master-funding-playbook",
    title: "Master Funding Playbook",
    subtitle: "End-to-End Funding Process & Controls",
    audience: "Senior operators, deal principals, private credit desks",
    category: "Funding Routes",
    description:
      "Comprehensive playbook for TROPTIONS-assisted funding transactions: deal intake, asset review, route selection, document package, lender engagement, and closing controls.",
    pdfPath: "/troptions/downloads/master-funding-playbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/docs/funding-playbook", "/troptions/funding"],
    requiredFor: ["Deal principal review", "Private credit desk onboarding"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "funding-route-matrix",
    title: "Funding Route Matrix",
    subtitle: "Side-by-Side Route Comparison & Eligibility",
    audience: "Asset owners, lenders, deal analysts",
    category: "Funding Routes",
    description:
      "Quick-reference matrix comparing all TROPTIONS funding routes: minimum asset value, route type, typical timeline, required documents, approval authority, and current status.",
    pdfPath: "/troptions/downloads/funding-route-matrix.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes"],
    requiredFor: ["Route selection analysis", "Lender pre-qualification"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "client-intake-document-checklist",
    title: "Client Intake Document Checklist",
    subtitle: "Master Document Request for All Asset Types",
    audience: "Asset owners, attorneys, deal coordinators",
    category: "Onboarding / KYC",
    description:
      "Master checklist covering all document categories required for TROPTIONS client intake: identity, entity, asset title, legal authority, financial, and compliance documents.",
    pdfPath: "/troptions/downloads/client-intake-document-checklist.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/kyc", "/troptions/onboarding"],
    requiredFor: ["All transaction onboarding", "Asset owner intake"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-funding-procedure",
    title: "PATE-COAL-001 Funding Procedure",
    subtitle: "Step-by-Step Funding Process for Pate Prospect",
    audience: "Asset owner, deal coordinator, lender",
    category: "PATE-COAL-001",
    description:
      "Step-by-step funding procedure for the Pate Prospect coal/mineral-rights RWA: current readiness score (40/100), hard blockers, required document sequence, approval gates, and route recommendations.",
    pdfPath: "/troptions/downloads/pate-coal-001-funding-procedure.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal", "/troptions/funding-routes"],
    requiredFor: ["PATE-COAL-001 funding initiation"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-lender-review-packet",
    title: "PATE-COAL-001 Lender Review Packet",
    subtitle: "Executive Summary, Readiness Score & Financing Routes",
    audience: "Lenders, private credit desks, diligence teams",
    category: "PATE-COAL-001",
    description:
      "Comprehensive lender-facing overview of the Pate Prospect asset: uploaded evidence, 40/100 readiness score, 8 hard-blocker checklist, recommended routes, and Aave hard-block explanation.",
    pdfPath: "/troptions/downloads/pate-coal-001-lender-review-packet.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal"],
    requiredFor: ["Lender initial review", "Private credit desk intake"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-owner-document-request",
    title: "PATE-COAL-001 Owner Document Request",
    subtitle: "Checklist: Title, Mineral Rights, Permits, Legal, Commercial",
    audience: "Asset owner, legal counsel",
    category: "PATE-COAL-001",
    description:
      "Formatted checklist for the PATE-COAL-001 asset owner covering all 9 document categories: title/deed, mineral rights, tax/lien/UCC, engineering, permitting/environmental, commercial/offtake, legal authority, funding terms, and XRPL receipt readiness.",
    pdfPath: "/troptions/downloads/pate-coal-001-owner-document-request.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal"],
    requiredFor: ["Asset owner document submission"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-route-verification-guide",
    title: "PATE-COAL-001 Route Verification Guide",
    subtitle: "Deployment Checklist & Route Verification Procedures",
    audience: "Deal coordinators, technical operators",
    category: "PATE-COAL-001",
    description:
      "Post-deployment verification guide: all 5 PATE-COAL-001 routes, expected API responses, verification commands, and simulationOnly enforcement strings.",
    pdfPath: "/troptions/downloads/pate-coal-001-route-verification-guide.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal"],
    requiredFor: ["Route deployment verification"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "axl-001-rwa-financing-checklist",
    title: "AXL-001 RWA Financing Checklist",
    subtitle: "Asset Financing Readiness & Due Diligence",
    audience: "Asset owners, lenders, compliance officers",
    category: "RWA / Asset Packages",
    description:
      "Complete financing checklist for the AXL-001 RWA package: asset verification, legal wrapper, custody confirmation, lender requirements, and approval conditions.",
    pdfPath: "/troptions/downloads/axl-001-rwa-financing-checklist.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/axl-001"],
    requiredFor: ["AXL-001 financing initiation", "Lender submission"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "legacy-token-migration-handbook",
    title: "Legacy Token Migration Handbook",
    subtitle: "Migration Procedures, Eligibility & Controls",
    audience: "Legacy token holders, compliance teams",
    category: "Legacy / Buyback / LP Review",
    description:
      "Guide to legacy TROPTIONS token migration: eligibility criteria, document requirements, migration workflow, approval gates, and what remains blocked pending legal and compliance review.",
    pdfPath: "/troptions/downloads/legacy-token-migration-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/migration", "/troptions/legacy"],
    requiredFor: ["Legacy token holder intake", "Migration approval"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "buyback-review-handbook",
    title: "Buyback Review Handbook",
    subtitle: "Token Buyback Readiness & Approval Gates",
    audience: "Token holders, governance participants",
    category: "Legacy / Buyback / LP Review",
    description:
      "Review handbook for TROPTIONS token buyback programs: readiness criteria, legal requirements, governance approval process, treasury controls, and what remains blocked until approvals complete.",
    pdfPath: "/troptions/downloads/buyback-review-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/treasury"],
    requiredFor: ["Buyback governance review"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "liquidity-pool-readiness-handbook",
    title: "Liquidity Pool Readiness Handbook",
    subtitle: "LP Setup, Compliance & Approval Requirements",
    audience: "DeFi operators, liquidity providers, compliance teams",
    category: "Legacy / Buyback / LP Review",
    description:
      "Readiness guide for TROPTIONS liquidity pool participation: legal entity requirements, KYC/AML controls, smart contract audit requirements, governance approval gates, and current status. All LP execution remains blocked pending approvals.",
    pdfPath: "/troptions/downloads/liquidity-pool-readiness-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/xchange"],
    requiredFor: ["LP participation approval"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "wallet-mint-noncustodial-guide",
    title: "Wallet Mint / Non-Custodial Wallet Guide",
    subtitle: "Wallet Setup, XRPL Trustlines & Non-Custodial Controls",
    audience: "Participants, operators, asset owners",
    category: "XRPL / IOU / Wallets",
    description:
      "Guide to TROPTIONS non-custodial wallet setup: XRPL wallet creation, trustline establishment, reserve requirements, security controls, and non-custodial usage. No custody or exchange functionality is enabled.",
    pdfPath: "/troptions/downloads/wallet-mint-noncustodial-guide.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/wallets", "/troptions/xrpl-platform"],
    requiredFor: ["Wallet onboarding", "XRPL participant setup"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "rust-runtime-control-layer-overview",
    title: "Rust Runtime / L1 Control Layer Overview",
    subtitle: "Layer 1 Architecture, Consensus & Governance",
    audience: "Technical operators, node operators, governance participants",
    category: "Core Platform",
    description:
      "Technical overview of the TROPTIONS Rust L1 control layer: crate architecture, consensus model, governance controls, bridge interfaces, and deployment requirements.",
    pdfPath: "/troptions/downloads/rust-runtime-control-layer-overview.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/layer1"],
    requiredFor: ["Node operator onboarding", "L1 governance participation"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
] as const;

export const PDF_SAFETY_DISCLAIMER =
  "TROPTIONS materials are provided for informational and due-diligence purposes only. TROPTIONS is not a bank, broker-dealer, exchange, custodian, licensed financial institution, investment adviser, or legal adviser. No live custody, exchange, stablecoin issuance, IOU issuance, Aave execution, token buyback, liquidity pool execution, mining operation, or public investment functionality is enabled. All execution requires legal, compliance, provider, custody, signer, and governance approvals.";

export const PDF_FILENAMES = [
  "troptions-platform-overview.pdf",
  "kyc-onboarding-handbook.pdf",
  "rwa-tokenisation-handbook.pdf",
  "carbon-credit-handbook.pdf",
  "bitcoin-settlement-handbook.pdf",
  "xrpl-iou-issuance-handbook.pdf",
  "funding-routes-handbook.pdf",
  "master-funding-playbook.pdf",
  "funding-route-matrix.pdf",
  "client-intake-document-checklist.pdf",
  "pate-coal-001-funding-procedure.pdf",
  "pate-coal-001-lender-review-packet.pdf",
  "pate-coal-001-owner-document-request.pdf",
  "pate-coal-001-route-verification-guide.pdf",
  "axl-001-rwa-financing-checklist.pdf",
  "legacy-token-migration-handbook.pdf",
  "buyback-review-handbook.pdf",
  "liquidity-pool-readiness-handbook.pdf",
  "wallet-mint-noncustodial-guide.pdf",
  "rust-runtime-control-layer-overview.pdf",
] as const;
